### ISSUE TITLE
Feature Request - Extended rules around Druid forms

### ISSUE THREAD

**Issue by Soromeister** [RavenousAddons/ravMounts#34]
**This is a feature request, not a bug.**

## Expected behaviour
I have the below macro (it's not perfect):
```
#showtooltip
/use [advflyable,nocombat]Flourishing Whimsydrake
/use [outdoors,flyable]Travel Form;[harm]Moonkin Form;[indoors]Cat Form
/use [outdoors]Travel Form
/dismount [mounted]
```
The intended use is like so:
- If I am in a zone where I can use Dragonriding mount, use it.;
- If that is not available, use the druid travel form instead. This works with my macro when I am walking and pressing the button, since it'll get me in druid form, as dragon riding is not available while walking, since there is a cast time to it;
- If I have a target that I can attack, put me in Moonkin form;
- Indoors, use cat form;
- Underwater, use travel form;
- Pressing again will dismount/dispel the druid form;

## Actual behaviour
I am looking to get similar functionality with Rav Mounts although the add-on has an exclusive switch on the druid forms:
- If I use druid forms, it will always put me in Druid flight form even though I should be able to dragonride;
- If I don't use druid forms, cat form is not casted indoors. I suspect the same with underwater travel form;
- I am unable to use "Alternate Mounts Modifier" since I already have other buttons bound to all modifier keys so I wouldn't want to change that just for this. So the macro is bound to `-`, Moonkin form is bound to `SHIFT + -` (because sometimes I just need to Moonkin directly without satisfying the macro conditions), Brutosaur is on `CTRL + -` and Yak is on `ALT + -`.

## Steps to reproduce this behaviour

1. Use a druid
2. Use my macro and see how it behaves
3. Attempt to reproduce this in Ravenous Mounts add-on

@waldenp0nd

**Comment by waldenp0nd** [comment]
Hey @Soromeister,

Sorry to just get back to you.

Thanks for the feature request! There have been some glaring issues with how the addon handles class forms for a while now, so this is high on the list of priorities for me to attend to. The last time I tried to address those issues, I ended up breaking the addon for *all classes* 😅 so I will have to tread very carefully and test extremely thoroughly before I release a fix here.

I appreciate that a lot of time has passed since you submitted this feature request, and you've likely moved onto another addon that *does* support what you're looking for, but I thank you nonetheless for bringing this to my attention as a critical piece of the addon that needs fixing!

**Comment by Soromeister** [comment]
Hi @waldenp0nd , I haven't moved to another addon, but I am using my own macro (as faulty as it is). I am looking forward to the major refactor update. Thanks.

**Comment by waldenp0nd** [comment]
Hey @Soromeister, unfortunately I've made the decision to stop development on Ravenous Mounts.

I can't recommend [LiteMount](https://www.curseforge.com/wow/addons/litemount) enough if you're looking for another addon that provides nearly all the same functionality as Ravenous Mounts!
